### ISSUE TITLE
[Widget] Jenkins

### ISSUE THREAD

**Issue by danielbayerlein** [danielbayerlein/dashboard#3]

**Comment by chrishelgert** [comment]
magic happens in [jenkins branch](https://github.com/danielbayerlein/dashboard/tree/jenkins).

* widget exists
* connected to ci.jenkins-ci.org and show 2 Builds
* for further styling i will wait for #2 (cause of loadingIndicator, table and badges)

@danielbayerlein what do you think about
![bildschirmfoto 2017-05-05 um 17 25 58](https://cloud.githubusercontent.com/assets/3918488/25752235/f3964a40-31b7-11e7-8d5b-9bfd399919b1.png)

instead of aborted and failure will be nice badges :)
